### ISSUE TITLE
Not compatible with the latest PHPUnit Version 9.*

### ISSUE THREAD

**Issue by michaelprankl99** [clagiordano/phpunit-result-printer#1]
Cannot be used with latest PHPUnit version.
![image](https://user-images.githubusercontent.com/46670585/97859943-97918000-1d01-11eb-8a58-df2a5340523c.png)

**Comment by clagiordano** [comment]
@michaelprankl99 thanks for your feedback, currently version 2.x supports phpunit `^7|^8` to support v9 of phpunit some adaptation work is required as some internal phpunit classes on which this package is based have changed, 
as soon as possible I would like to release a v3 of this package based on phpunit v9.

**Comment by clagiordano** [comment]
@michaelprankl99 A new version (v3) of this package has been released to add compatibility with phpunit v9 (#2)

I've also added on main README.md file a compatibility table quickly find the right version for most common systems (#3), I hope that these changes can be helpful for you.
